iVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  replicas: 3  # Number of replicas you want to run
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
        - name: my-python-app
          image: njogubless1/my-python-app # The Docker image for your web application
          ports:
            - containerPort: 80  # The port on which your web application listens
          # Additional configuration for environment variables, volumes, etc.
