---
- name: Configure web server
  hosts: webserver
  become: true

  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
        - nginx

    - name: Install Python packages
      pip:
        name: uwsgi
        state: present
        virtualenv: /path/to/your/virtualenv

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/your_app.conf
      notify:
        - Restart Nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/your_app.conf
        dest: /etc/nginx/sites-enabled/your_app.conf
        state: link

    - name: Disable default Nginx site
      file:
        src: /etc/nginx/sites-enabled/default
        dest: /etc/nginx/sites-enabled/default
        state: absent

    - name: Deploy application
      copy:
        src: your_app.py
        dest: /path/to/your/app/your_app.py
      notify:
        - Restart uWSGI

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Restart uWSGI
      systemd:
        name: uwsgi
        state: restarted
