---
- name: Configure and deploy web server
  hosts: web_servers
  become: true
  gather_facts: true

  tasks:
    - name: Update packages
      apt:
        upgrade: true
        update_cache: true

    - name: Install dependencies
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy Nginx configuration
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - Restart Nginx

    - name: Enable and start Nginx
      service:
        name: nginx
        enabled: true
        state: started

    - name: Deploy the Python application
      copy:
        src: app.py
        dest: /var/www/myapp/app.py
      notify:
        - Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
